# Generated by Django 3.1.4 on 2020-12-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20201212_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='u_dob',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='s_dob',
        ),
        migrations.AddField(
            model_name='customer',
            name='conf_pswd',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pswd',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='conf_pswd',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='pswd',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
